// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote(arg1:string,arg2:string):Promise<main.Note>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetNote(arg1:string):Promise<main.Note>;

export function GetNotes():Promise<Array<main.Note>>;

export function UpdateNote(arg1:string,arg2:string,arg3:string):Promise<main.Note>;
