name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24.4"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.os == 'ubuntu-22.04'
        with:
          packages: libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config
          version: 1.0

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build application
        run: wails build

      - name: Package application
        run: |
          mkdir -p release
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a -tzip release/NoteApp-${{ github.ref_name }}-windows-amd64.zip ./build/bin/NoteApp.exe
          elif [ "${{ runner.os }}" == "macOS" ]; then
            zip -r release/NoteApp-${{ github.ref_name }}-darwin-amd64.zip ./build/bin/NoteApp.app
          else
            zip -j release/NoteApp-${{ github.ref_name }}-linux-amd64.zip ./build/bin/NoteApp
          fi
        shell: bash

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
